#!/usr/bin/env groovy
pipeline {
    agent any
    tools {nodejs "nodejs"}
    stages {
        stage('Build-back') {
            steps {
                sh '''cd back
                npm install -g yarn
                yarn dev'''
            }
        }
        stage('Build-front') {
            steps {
                sh '''cd frontend
                npm install -g yarn
                yarn dev'''
            }
        }
    }
}