#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('Build-back') {
            steps {
                sh '''cd back'''
            }
        }
        stage('Build-front') {
            steps {
                sh '''cd frontend'''
            }
        }
    }
}